// See README.md for license details.

package xor_reduce

import chisel3._

/**
  * This provides an alternate way to run tests, by executing then as a main
  * From sbt (Note: the test: prefix is because this main is under the test package hierarchy):
  * {{{
  * test:runMain xor_reduce.XorReduceMain
  * }}}
  * To see all command line options use:
  * {{{
  * test:runMain xor_reduce.XorReduceMain --help
  * }}}
  * To run with verilator:
  * {{{
  * test:runMain xor_reduce.XorReduceMain --backend-name verilator
  * }}}
  * To run with verilator from your terminal shell use:
  * {{{
  * sbt 'test:runMain xor_reduce.XorReduceMain --backend-name verilator'
  * }}}
  */
object XorReduceMain extends App {
  iotesters.Driver.execute(args, () => new XorReduce) {
    c => new XorReduceUnitTester(c)
  }
}

/**
  * This provides a way to run the firrtl-interpreter REPL (or shell)
  * on the lowered firrtl generated by your circuit. You will be placed
  * in an interactive shell. This can be very helpful as a debugging
  * technique. Type help to see a list of commands.
  *
  * To run from sbt
  * {{{
  * test:runMain xor_reduce.XorReduceRepl
  * }}}
  * To run from sbt and see the half a zillion options try
  * {{{
  * test:runMain xor_reduce.XorReduceRepl --help
  * }}}
  */
object XorReduceRepl extends App {
  iotesters.Driver.executeFirrtlRepl(args, () => new XorReduce)
}